remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true #["true" or "false" (unquoted) to indicate whether to provide a download URL]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  
title: CSPB-3112 Protfolio
description: This is an example site to show an example portfolio for CCSPB 3112
